### PR TITLE
doc: add Traditional Chinese

### PR DESCRIPTION
**Pull request by AlanSyue**
translate to Traditional Chinese, hope to merge in this repo, thanks

### CODE REVIEW

**Comment by wojtekmaj** [comment]
Awesome, thanks!

**Comment by AlanSyue** [comment]
@wojtekmaj thanks, has it already deploy to server?

**Comment by wojtekmaj** [comment]
Nope, I'm on holidays at the moment ;)

**Comment by AlanSyue** [comment]
@wojtekmaj OK, have a nice vacation!

**Pull request merged**
