### PR TITLE
Add hu-HU translation

### PR DESCRIPTION
**Pull request by beahuszar**
Hi @wojtekmaj, you can find the Hungarian translation in this PR, hope you find it useful! :)

### CODE REVIEW

**Comment by beahuszar** [comment]
hi @wojtekmaj, did you have the chance to have a look at this pr? is anything else missing for the merge? :)

**Comment by wojtekmaj** [comment]
My Hungarian skills end on jó reggelt, so I'll have to trust you on this :joy:

**Comment by beahuszar** [comment]
Hi @wojtekmaj, thanks for the merge! 😊 if that's not a big issue, can you pls change my email address in the commit msg to `husz.beata@gmail.com`? I forgot to setup the gitconfig for the forked repo and that is my work email. 🙈

**Comment by beahuszar** [comment]
yayy thanks a lot! :)

**Pull request merged**
